name: Biweekly Forecast

# Trigger workflow on a schedule and manually
on:
  schedule:
    # Runs at 10:00 AM GST (6:00 AM UTC) on the 1st and 15th of every month
    - cron: "0 6 1,15 * *"
  workflow_dispatch:

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Run ML forecast scripts
    - name: Run ML scripts
      run: |
        mkdir -p outputs
        python scripts/ml_train.py
        python scripts/ml_predict.py
        # Move generated files to outputs folder if needed
        # mv <generated_file> outputs/

    # 5️⃣ Upload outputs as GitHub artifacts
    - name: Upload forecast outputs
      uses: actions/upload-artifact@v3
      with:
        name: forecast-outputs
        path: outputs/
